# Generated by Django 3.2.7 on 2021-09-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
