# Generated by Django 3.2.7 on 2021-09-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, null=True)),
                ('course_trainer', models.CharField(max_length=12, null=True)),
                ('course_code', models.CharField(max_length=12, null=True)),
                ('course_description', models.FileField(null=True, upload_to='documents/')),
                ('course_duration', models.PositiveSmallIntegerField(null=True)),
                ('syllabus', models.TextField(max_length=700, null=True)),
            ],
        ),
    ]
