# Generated by Django 3.2.7 on 2021-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'male'), ('3', 'none')], max_length=8, null=True)),
                ('bio', models.TextField(max_length=700, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('salary', models.PositiveBigIntegerField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('contract', models.FileField(null=True, upload_to='documents/')),
                ('date_hired', models.DateField(null=True)),
            ],
        ),
    ]
