# Generated by Django 3.2.7 on 2021-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=20, null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('nationality', models.CharField(choices=[('1', 'Rwandan'), ('2', 'Kenyan'), ('3', 'Ugandan'), ('4', 'South Sudanese'), ('5', 'Sudanese')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'male'), ('3', 'none')], max_length=8, null=True)),
                ('guardian_name', models.CharField(max_length=12, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('district', models.CharField(max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('date_of_enrollment', models.DateField(null=True)),
                ('course_name', models.CharField(max_length=18, null=True)),
                ('languages', models.CharField(choices=[('1', 'English'), ('2', 'Kinyarwanda'), ('3', 'French'), ('4', 'Kiswahili'), ('5', 'Luganda')], max_length=20, null=True)),
                ('laptop_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
